### ISSUE TITLE
Change JSONRepresentation to JSONString for PhoneGap 1.3

### ISSUE THREAD

**Issue by brody2consult** [davibe/Phonegap-SQLitePlugin#17] opened 2012-03-21 07:07 UTC
README.md indicates that the name of the header file was changed JSON.h to JSONKit.h in PhoneGap 1.3. In addition, `[resultSet JSONString]` must be used in place of `[resultSet
JSONRepresentation]` in `Plugins/PGSQLitePlugin.m`. I will post a pull request with this fix in `README.md`. Please bear with me that this is my first time using github and I am also just starting using Objective-C.

**Comment by brody2consult** [comment] 2012-03-21 07:44
I have just posted [pull request #18](https://github.com/davibe/Phonegap-SQLitePlugin/pull/18) to fix the documentation in README.md.

**Comment by davibe** [comment] 2012-03-23 06:47
this is a duplicate of #17, from the same person

**Closed as completed** 2012-03-23 07:16 UTC
